const IMAGE_DATA = 'IMAGE_DATA';
const LOGIN_DATA = 'LOGIN_DATA';
const SCORE_DATA = 'SCORE_DATA';
const HOME_DISPATCH = 'HOME_DISPATCH';

export { IMAGE_DATA, LOGIN_DATA, SCORE_DATA, HOME_DISPATCH };
